define({
    root: ({
        exportCsv: "Export CSV",
        apply: "Apply",
        renderer: "Renderer",
        publish: "Publish",
        bands: "Bands",
        close: "Close",
        root: "Root",
        tags: "Tags",
        result: "result",
        next: "Next",
        description: "Description",
        name: "Name",
        folder: "Folder",
        searchTools: "Search Tools",
        selectArea: "Select Area",
        searchCurrentExtent: "Search in Current Extent",
        searchByRectangle: 'Search By Rectangle',
        searchAtPoint: "Search at Point",
        searchByBounds: "Search by Bounds",
        search: "Search",
        clear: "Clear",
        pointBufferOptional: "Point Buffer (optional)",
        distance: "Distance",
        meter: "Meter",
        kilometer: "Kilometer",
        servicesToSearch: "Services to Search",
        searchingForImagery: "Searching for imagery",
        previewArchivedImagery: "Preview archived imagery",
        viewImageryInformation: "View Imagery Information",
        filterYourResults: "Filter your results",
        changeSortOrder: "Change the sort order of your results",
        changeDrawOrder: "Change the drawing order of your imagery once added to the map",
        setLayerProperties: "Set imagery layer properties",
        itemsInCart: "Items in cart",
        goToCart: "Go to Cart",
        resultTools: "Result Tools",
        errorQueryingService: "Error querying service",
        invalidGeometry: "Invalid Geometry",
        iconError: "Icon Error",
        noServiceToSearch: "No service to search",
        downloadImagery: "Download Imagery",
        createWebmap: "Create Web Map",
        reviewAndSubmit: "Review and Submit",
        confirmation: "Confirmation",
        couldNotRetrieveCurrentBasemap: "Could not retrieve base current map",
        couldNotGenerateReport: "Could not generate report",
        format: "Format",
        title: "Title",
        myReport: "My Report",
        layoutTemplate: "Layout Template",
        landscape: "Landscape",
        portrait: "Portrait",
        letter: "Letter",
        viewYourWebmap: "View Your Web Map",
        signInToPublishWebmap: "Sign in to publish Web Map",
        done: "Done",
        shareWith: "Share with",
        everyone: "Everyone",
        public: "Public",
        theseGroups: "These Groups",
        back: "Back",
        webmapCreationSuccessful: "Web Map Creation Successful",
        errorPublishingWebmap: "There was an error publishing your Web Map",
        mustProvideWebmapName: "You must provide a name for the web map",
        mustProvideWebmapTag: "You must provide a tag for the web map",
        errorDownloadingFile: "Error downloading file",
        yourFilesHaveBeenPrepared: "Your Files Have Been Prepared",
        clickThe: "Click the",
        iconOnAnItemDownload: "icon on an item to download",
        zoomToSearchArea: "Zoom To Search Area",
        showOnlyCartItems: "Show Only Items In Cart",
        sortResults: "Sort Results",
        configureResults: "Configure Results",
        layerDisplayProperties: "Layer Display Properties",
        reorderPreviewImages: "Reorder Preview Images",
        clearResults: "Clear Results",
        searchReturned: "Search returned",
        addPreviewImageToMap: "Add a preview image to the map",
        removePreview: "Remove Preview",
        dateRange: "Date Range",
        percentCloudCover: "Percent Cloud Cover",
        platforms: "Platforms",
        clearPreviews: "Clear Previews",
        sortBy: "Sort By",
        dd: "DD",
        utm: "UTM",
        dms: "DMS",
        upperRight: "Upper Right",
        lowerLeft: "Lower Left",
        x: "x",
        y: "y",
        easting: "easting",
        northing: "northing",
        zone: "zone",
        hemisphere: "hemisphere",
        S: "S",
        N: "N",
        imageMode: "Image Mode",
        pixelSize: "Pixel Size",
        searchParameters: "Search Parameters",
        maxCloudCover: "Max. Cloud Cover",
        min: "Min",
        max: "Max",
        imagePreview: "Image Preview",
        info: "Info",
        preview: "Preview",
        noProjectGeometries: "No geometries to project",
        cannotProcessProject: "Cannot process project",
        selectALayer: "Select a Layer",
        transparency: "Transparency",
        startDate: "Start Date",
        endDate: "End Date",
        band: "Band",
        addToCart: "Add To Cart",
        removeFromCart: "Remove From Cart",
        remove: "Remove",
        save: "Save",
        cannotPublishWebMap: "Cannot publish Web Map. Web Map name already exists.",
        csvExport: "Export CSV",
        exportResults: "Export Results",
        imageServices: "Image Services",
        noLocalDownloadSupport:"Your browser does not support local downloads. Your CSV export will open in a new browser window.",
		zoomError: "Zoom in to activate Image Discovery"
    }),
    fr: 1
});