define({
    root:({		
		enableImageSelector: "Enable Image Selector",
		setCurrentAsSecondaryLayer: "Set Current as Secondary Layer.",
		showImageInDropdown: "Show images in drop down list.",
		refreshQuery: "Refresh query based on current extent.",
		show: "Show",
		image: "Image",
		footprint: "Footprint",
		age: "Age",
		day: "Day(s)",
		week: "Week(s)",
		month: "Month(s)",
		year: "Year(s)",
		zoomImage: "Zoom in to select images.",
		fieldNotSpecified: "Field is not specified.",
		noObjectIdField: "No ObjectID field.",
		noCategoryField: "No Category field.",
		error: "Cannot perform action for layer.",
		serviceNotSupported: "Services pre 10.2.1 not supported.",
		layer: "Layer",
		visibilityOff: "Visibility Off",
		noVisibleImageryLayer: "No visible Imagery Layers in the map.",
		largeZoom: "LARGE zoom: ",
		thresholdZoom: "THRESHOLD zoom: ",
		largePan: "LARGE pan: ",
		showImageOnSlider: "Show images on slider.",
		noSceneInCurrentExtent: "No scenes in current extent.",
		date: "Date(s)",
		warning: "Number of footprints selected exceed 20. Only first 20 will be displayed. Press OK not to warn again."				
    })
});