define({
    root: ({
        searchServices: "Search Services",
        imageServiceUrl: "Image Service URL",
        goToCart: "Go to Cart",
        reviewAndSubmit: "Review and Submit",
        newest: "Newest",
        oldest: "Oldest",
        leastCloudCover: "Least Cloud Cover",
        mostCloudCover: "Most Cloud Cover",
        serviceAlreadyAdded: "service already added",
        addSearchService: "Add Image Service",
        load: "Load",
        NO_FIELD: "NO FIELD",
        source: "Source",
        removeService: "Remove Service",
        collapse: "Collapse",
        displayName: "Display Name",
        downloadEnabled: "Download Enabled",
        sortFields: "Sort Fields",
        cloudCover: "Cloud Cover",
        acquisitionDate: "Acquisition Date",
        displayFields: "Display Fields",
        displayIn: "Display In",
        entry: "Entry",
        infoPopup: "Info Popup",
        label: "Label",
        valueAppend: "Value Append",
        floatPrecision: "Float Precision",
        bold: "Bold",
        showCloudCoverSort: "Cloud Cover Sort",
        showAcquisitionDateSort: "Acquisition Date Sort",
        sortingConfiguration: "Sort Configuration",
        enableWebmapCheckout: "Web Map Checkout",
        checkoutConfiguration: "Checkout Configuration",
        enableCSVCheckout: "CSV Export",
        sensorAZ: "A-Z Sensor",
        sensorZA: "Z-A Sensor"
    }),
    fr: 1
});