define(
    ({
        goToCart: "Aller au panier",
        reviewAndSubmit: "Et à soumettre",
        newest: "Date",
        oldest: "Le plus ancien",
        leastCloudCover: "Moins couverture nuageuse",
        mostCloudCover: "La plupart couverture nuageuse",
        serviceAlreadyAdded: "service déjà ajouté",
        addSearchService: "Ajouter un service de Recherche",
        load: "charge",
        NO_FIELD: "Aucun champ",
        source: "source",
        removeService: "supprimer le Service",
        collapse: "effondrement",
        displayName: "Nom D'Affichage",
        downloadEnabled: "Télécharger Enabled",
        sortFields: "Trier les champs",
        cloudCover: "Couverture nuageuse",
        acquisitionDate: "date d'acquisition",
        displayFields: "Afficher les champs",
        displayIn: "Affichage en",
        entry: "Entrée",
        infoPopup: "Infos Popup",
        label: "étiquette",
        valueAppend: "valeur Append",
        floatPrecision: "float précision",
        bold: "audacieux"
    })
);