define({
    root:({		
		mode: "Mode",
		saveToPortal: "Save to Portal",
		saveToDisk: "Save To Disk",
		title: "Title",
		description: "Description",
		tags: "Tags",
		defineExtent: "Define Extent",
		submit: "Submit",
		pixelSize: "Pixel Size",
		outputSpatialReference: "Output Spatial Reference",
		currentRenderer: "Current Renderer",
		note: "Note",
		currentRendererChecked: "If Current Renderer is checked, the rendering",
		originalDataValues: "is exported, else the original data values",
		exported: "will be exported.",
		export: "Export",
		exportImage: "Export Image",
		layerSaved: "Layer saved.",
		error: "Error! ",
		errorNotification: "Error! No Imagery Layer visible on the map.",
		utmZone: "WGS84 UTM Zone ",
		WKID: "WKID : ",
		webMercatorAs: "WebMercatorAS",
		default: "Default",
		pixelSizeRestricted: "PixelSize of export is restricted to ",
		thisExtent: " for this extent.",
		errorPixelSize: "Error! No Imagery Layer visible on the map.",
		layer: "Layer",
		exportLayerMsg: "No visible imagery layers on the map."		
    }),
    "ar": 1,
    "fr": 1
});