define({
	  orderBy: "",
	  onlyScale: "",
	  attribute: "",
	  imageCenter: "",
	  fixedOrder: "",
	  sensorLocation: "",
	  viewPoint: "",
	  definedSeamlines: "",
	  listOfImages: "",
	  reverseOrder: "",
	  mosaicOperation: "",
	  highestPriority: "",
	  blendPixelValue: "",
	  minimumPixel: "",
	  maximumPixel: "",
	  averagePixel: "",
	  attribute: "",
	  priority: "",
	  imageId: "",
	  apply: "",
	  layer: "",
	  error: "",
      requestFailed: ""	  
});