define(
    ({
        apply: "Appliquer",
        renderer:"Rendu",
        publish:"Publier",
        bands:"Bandes",
        close:"Près",
        root:"Racine",
        tags:"Mots clés",
        result:"Résultat",
        next:"Suivant",
        name:"Nom",
        folder:"Dossier",
        searchTools:"Outils de recherche",
        selectArea:"Choisissez la région",
        searchCurrentExtent:"Recherche étendue actuelle",
        searchByRectangle:"Préciser par Rectangle",
        searchAtPoint:"Recherche à Point",
        searchByBounds:"Recherche par Bounds",
        search:"Recherche",
        clear:"Clair",
        pointBufferOptional:"Point de tampon (en option)",
        meter:"Mètre",
        kilometer:"Kilomètre",
        servicesToSearch:"Services Rechercher",
        searchingForImagery:"Recherche d'images",
        previewArchivedImagery:"Aperçu Archivée Images",
        viewImageryInformation:"Voir Imagerie Information",
        filterYourResults:"Filtrez vos résultats",
        changeSortOrder:"Modifier l'ordre de tri de vos résultats",
        changeDrawOrder:"Modification de l'ordre de dessin de vos images une fois ajoutés à la carte",
        setLayerProperties:"Propriétés de la couche d'imagerie Set",
        itemsInCart:"Articles dans le panier",
        goToCart: "Aller au panier",
        resultTools:"Outils de résultat",
        errorQueryingService:"Un service d'interrogation d'erreur",
        invalidGeometry:"Géométrie non valide",
        iconError:"Icône Erreur",
        noServiceToSearch:"Aucun service de recherche",
        downloadImagery:"Télécharger imagerie",
        createWebmap:"Créer Webmap",
        reviewAndSubmit:"Et à soumettre",
        couldNotRetrieveCurrentBasemap:"Impossible de récupérer la carte courant de base",
        couldNotGenerateReport:"Impossible de générer un rapport",
        title:"Titre",
        myReport:"Mon rapport",
        layoutTemplate:"Modèle Disposition",
        landscape:"Paysage",
        portrait:"Portrait",
        letter:"Lettre",
        viewYourWebmap:"Voir votre Webmap",
        signInToPublishWebmap:"Connectez-vous pour publier Webmap",
        done:"Fini",
        shareWith:"Partager avec",
        everyone:"Tout le monde",
        theseGroups:"Ces Groupes",
        back:"Arrière",
        webmapCreationSuccessful:"Webmap création réussie",
        errorPublishingWebmap:"Il y avait une erreur de publier votre plane du web",
        mustProvideWebmapName:"Vous devez fournir un nom pour la carte Web",
        mustProvideWebmapTag:"Vous devez fournir une étiquette pour voir la carte de web",
        errorDownloadingFile:"Fichier de téléchargement d'erreur",
        yourFilesHaveBeenPrepared:"Vos fichiers ont été préparés",
        clickThe:"Cliquez sur le",
        iconOnAnItemDownload:"Icône sur un élément à télécharger",
        zoomToSearchArea:"Zoom Pour Zone de Recherche",
        showOnlyCartItems:"Afficher uniquement les articles dans le panier",
        sortResults: "Sort Results",
        configureResults:"Configurez Résultats",
        layerDisplayProperties:"Afficher les propriétés des calques",
        reorderPreviewImages:"Réorganiser Preview Images",
        clearResults:"Effacer les résultats",
        searchReturned:"Recherche retourné",
        addPreviewImageToMap:"Ajouter une image d'aperçu à la carte",
        removePreview:"Retirer Aperçu",
        dateRange:"Date de Gamme",
        percentCloudCover:"Pour cent la couverture nuageuse",
        platforms:"Plates-formes",
        clearPreviews:"Previews claires",
        sortBy:"Trier Par",
        upperRight:"En haut à droite",
        lowerLeft:"En bas à gauche",
        easting:"Abscisse",
        northing:"Ordonnée",
        hemisphere:"Hémisphère",
        pixelSize:"Pixel Taille",
        searchParameters:"Paramètres de recherche",
        maxCloudCover:"Max. Couverture nuageuse",
        imagePreview:"Aperçu de l'image",
        preview:"Avant-Première",
        noProjectGeometries:"Aucune géométrie de projeter",
        cannotProcessProject:"Vous ne pouvez pas traiter projet",
        selectALayer: "Sélectionnez une couche",
        transparency: "Transparence",
        startDate: "Date de début",
        endDate: "Date de fin",
        addToCart: "Ajouter au panier",
        removeFromCart: "Retirer du panier",
        remove: "Supprimer",
        save: "Save",
        cannotPublishWebMap: "Cannot publish Web Map. Web Map name already exists."
    })
);