define({
    root:({		
		method: "Method",
		difference: "Difference",
		ndvi: "Vegetation Index",
		savi: "Soil Adjusted Veg.Index",
		water: "Water Index",
		burn: "Burn Index",
		differenceImage: "Difference Image",
		differenceMask: "Difference Mask",
		thresholdMask: "Threshold Mask",
		mode: "Mode",
		infraredBand: "Infrared Band",
		redBand: "Red Band",
		greenBand: "Green Band",
		shortWaveInfraredBand: "Short-wave Infrared Band",
		bandInputs: "Band Inputs",
		burntArea: "Burnt / Post Fire Regrowth Area",
		positive: "Positive",
		negative: "Negative",
		threshold: "Threshold",
		difference: "Difference",
		area: "Area Decrease / Increase",
		apply: "Apply",
        error : "IS ChangeDetection works with two scenes of different dates. Use IS ImageSelector to define a scene to compare with.<br/>Select a scene using the IS ImageSelector and then click on the <img src='widgets/ISChangeDetection/images/down.png' height='20'/> button. Return to this control to proceed with change detection."
    }),
    "ar": 1,
    "fr": 1,
});